- name: Clone dotfiles.
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  ansible.builtin.git:
    repo: "https://github.com/aaronjewell/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"

- name: Install dotfiles
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  shell: "{{ lookup('env', 'HOME') }}/dotfiles/install"
