---
- name: Clone ultimate vim.
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  ansible.builtin.git:
    repo: 'https://github.com/amix/vimrc.git'
    dest: "{{ lookup('env', 'HOME') }}/.vim_runtime"
    depth: 1

- name: Rename existing vimrc to overrides.
  become: true
  command: "mv {{ lookup('env', 'HOME') }}/.vimrc {{ lookup('env', 'HOME') }}/.ultimate_vim_overrides.vim"

- name: Install ultimate vim.
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  shell: "{{ lookup('env', 'HOME') }}/.vim_runtime/install_awesome_vimrc.sh"

- name: Connect dotfiles with ultimate vim.
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/.ultimate_vim_overrides.vim"
    dest: "{{ lookup('env', 'HOME') }}/.vim_runtime/my_configs.vim"
    state: link

- name: Install vim-numbertoggle.
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  ansible.builtin.git:
    repo: 'https://github.com/jeffkreeftmeijer/vim-numbertoggle.git'
    dest: "{{ lookup('env', 'HOME') }}/.vim_runtime/my_plugins/vim-numbertoggle"

- name: Install vim-gutentags.
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  ansible.builtin.git:
    repo: 'https://github.com/ludovicchabant/vim-gutentags.git'
    dest: "{{ lookup('env', 'HOME') }}/.vim_runtime/my_plugins/vim-gutentags"

- name: Install coc.
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  ansible.builtin.git:
    repo: 'https://github.com/neoclide/coc.nvim.git'
    dest: "{{ lookup('env', 'HOME') }}/.vim_runtime/my_plugins/coc"
    depth: 1
    version: release
